version: '3'
services:
  isweetv:
    image: leolitaly/isweetv:latest
    container_name: isweetv
    ports:
      - "8899:80"
    environment:
      - PASSWORD=${PASSWORD:-111111}
    restart: unless-stopped
