name: Build and Publish iSweeTv image

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish iSweeTv image
    runs-on: ubuntu-latest
    if: (github.event.workflow_run.conclusion == 'success' && github.repository == 'li-peifeng/iSweeTv') || (github.repository == 'li-peifeng/iSweeTv')

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
          
      - name: Set Docker image tags
        id: set-tags
        run: |
          if [ "${{ github.repository }}" = "li-peifeng/iSweeTv" ]; then
            echo "IMAGE_NAME=isweetv" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_NAME=isweetv-beta" >> $GITHUB_OUTPUT
          fi
          # 正确构造两个注册表的标签
          echo "DOCKERHUB_TAG=${{ secrets.DOCKER_USERNAME }}/${{ steps.set-tags.outputs.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
          echo "GHCR_TAG=ghcr.io/${{ github.repository_owner }}/${{ steps.set-tags.outputs.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.set-tags.outputs.DOCKERHUB_TAG }}
            ${{ steps.set-tags.outputs.GHCR_TAG }}
          platforms: linux/amd64,linux/arm64/v8
